### ISSUE TITLE
Automatic Facebook Authentication not working

### ISSUE THREAD

**Issue by nincehelser** [fbsamples/fbconsole#25]
I want to automatically authenticate into facebook without using a browser or any users involvement.  

I've tried several pieces of sample code that says it will do that, but I always come back to this error.  I think it might have something to do with a certificate?

Any insight would be appreciated.

Thanks!

Traceback (most recent call last):
  File "test.py", line 16, in <module>
    'http://local.fbconsole.com:8080/',
  File "/usr/local/lib/python2.7/dist-packages/fbconsole-0.3-py2.7.egg/fbconsole.py", line 427, in automatically_authenticate
    code = oauth["code"][0]
KeyError: 'code'

**Comment by LA9SHA** [comment]
Is it possible to get access to Facebook without any GUI and no manually input?

I want to add pictures by cron job from a Raspberry Pi.

**Comment by pcardune** [comment]
@LA9SHA, yes, but only if you already have an access token. It's not possible to get an access token without a GUI.  So you would have to get an access token beforehand and bake it in to your app. In this scenario, it would be a good idea to get a long lived access token that lasts for 60 days. Once you have that, you can refresh the access token periodically to make sure it continues to work.

**Comment by psineur** [comment]
OK, seems like this is long-standing issue and I'm not sure if mechanize is actually a way we want to support this...

I have no idea how it works for now & would recommend using existing tokens, which you can obtain for example with Graph Explorer: https://developers.facebook.com/tools/explorer/?method=GET&path=me

On a related note, we may want to provide similar functionality with device login in the near future: 
https://developers.facebook.com/docs/facebook-login/using-login-with-devices But it's still in the making and looks like is not available to everyone yet.

**Comment by kchr** [comment]
I'm sorry if this seems like a rant; it's just some quick thoughts on the matter...

Personally, I think making it possible to generate new tokens using only the API code (forcing the user to give away its user login credentials) would allow an application for silent access to a larger scope than the end-users intention, or even send the credentials to some other server before/after going to Facebook. It would also enable malicious applications to change the end-users password, effectively locking the user out.

I think doing it through a browser session is a good way for the end-user to have control over what permissions it hands over to any app using the API, making malicious/bad code less potent and keeps the user login credentials away from the application/API implementations. The impact of potentially malicious code is heavily reduced.

@LA9SHA :
> Is it possible to get access to Facebook without any GUI and no manually input?
> I want to add pictures by cron job from a Raspberry Pi.

As @pcardune already said: It's a one-time operation to get an access token. 

Depending on your use case you might want to register your own app key and get a credential token for that app (which does not expire until you specifically say so), instead of a simple user access token (which expire after some time). You will have to register for a developer account and get an app key, then use that app key/token in your application. It's a few steps extra compared to generating a user token using someone elses app key, but in return it only has to be done once. This way is probably, in 9 out of 10 cases, what you are looking for if you are writing CLI apps/scripts which doesn't require user input or a GUI.

Registering as a developer and getting an app token is done here:
[https://developers.facebook.com/apps](developers.facebook.com/apps).

The browser verification step part where you allow the application to access your profile is inevitable because of the security reasons mentioned in the beginning of this reply, but it really only has to be done once.

**Comment by lsoltero** [comment]
Hello All,

So i have fbconsole with automatically_authenticate working... almost... and need your help.

bottom line... i can use fbconsole with the credentials for my fb account to post to /me/feed and /me/photos.  yay!  the problem is that I can't do it for anyone else. 

Here is what I have done.
A. create a facebook app.
1.record APP_ID and Secret
2. set website URL to a real URL.  It seems that autmatically_authenticate does not require a call back URL (as normal authenticate does) so just need to have the address of an actual web URL. this is required to keep FB happy.  so i have http://www.globalmarinenet.com set for the site URL.
3. advanced->client oauth login enabled
4. app is public and available to all users

B. Here is a simple python script that i have been using to test authentication.
#!/usr/local/bin/python

import urllib
import fbconsole
import sys,os,os.path
sys.path.append("/usr/local/gmnlib/xgate/facebook")

fbconsole.OAUTH_SCOPE = ['publish_stream', 'read_stream']
fbconsole.APP_ID='XXXXXX'
fbconsole.automatically_authenticate('EMAIL', 'PW', 'SECRET', 'http://www.globalmarinenet.com/', True)

profile_pic = fbconsole.graph_url('/zuck/picture')
url=urllib.urlretrieve(profile_pic, 'zuck.jpg')
print profile_pic

when executed with my credentials (the owner of the app) it works perfectly.  I have another more complex script that allows me to upload pix/caption to the photos gallery without issue.  However, If i try anyone else's credentials the post fails.

Anyone have any ideas why?

do i need to go through the process of a review to get this to work for everyone?  I noticed that my App has the following approved items email, public_profile, user_friends. The permissions for posting seem to be missing.  When I start the review process FB asks how to test the app and what the login procedure is.  Not sure how to explain that we are using fbconsole or how to make the app available for them to test.  

I have added testers and developers to the app and tried using their email and pw but that also fails.

Any thoughts on how to allow fbconsole to post for any user providing valid credentials would greatly be appreciated.

--luis

**Comment by psineur** [comment]
Hey! So long story short - automatic auth is a tricky thing, that doesn't work for me at all. It's not a part of API or anything we provide to developers officially...
It probably will go away completely with reqeusts lib pull request merged & never come back.

The app review is a separate process, and has nothing to do with fbconsole nor graph explorer - it's a new system that was introduced to make sure real world (working for real users) applications are requesting only permissions, that are actually used & required for their app.
To pass through review your app needs to be ready to use by normal non-technical users. If you use this app_id only for your internal testing while you're actually still working on your project - probably review team will suggest to use test users & developers on your app's dashboard to make permissions work.

As soon as your app is ready to be used by users - submit review & provide guidelines how everything is done and what is the flow of your app login with fb.

**Comment by lsoltero** [comment]
I find it curious that it doesn't work for you.   I was having the issue listed above with the 
code = oauth["code"][0]
KeyError: 'code'
error.

As stated there was no listener on localhost:8080 which was causing the process to give the error.

What I found was that as long as you put the url to a valid website as the call back the problem goes away.   For automatic_auth any valid url will work.  The response from FB sends a redirect which mechanize must process.  However... the response it not generated by the call back so the authentication code is processed correctly.

Please try it again using any valid web address and see if that works for you.  



--luis

**Comment by psineur** [comment]
no luck. Using debug = True I was able to repro the requests with browser and successfully authenticated in fb & then app, but within fbconsole - it's awlays the same thing.

Looks like redirect must happen after POSTing a form, but instead server returns 200.

**Comment by lsoltero** [comment]
So why would it work for me and not you? could it be the version of mechanize?

mechanize: "0.2.5"
python: 2.6.2
OS: FreeBSD

--luis

**Comment by lsoltero** [comment]
more on this issue... Although I continue to be able to use fbconsole to post to /me/feeds and /me/photos it only works for me.  I created a test facebook user, made him a developer, and then in apps for my account invited the test user to be a developer of the application.  The notice was sent to the test user, the test user accepted.  However, when posting as that user authentication fails with the errors reported here.

So... currently stumped.

--luis

**Comment by psineur** [comment]
Can be a setting on user profile, test facebook users are different a bit, the main problem is that login never was built to be automated this way, so having e.g 2-factor auth can kill it...

Mac OS, python 2.7.6, Mechanize 0.2.5.

OK, so for the short term - I'm going to continue without auto authentication support, if anyone will have a patch that works for them - that's fine we can merge. If not - long term access tokens can be used instead ( https://developers.facebook.com/docs/facebook-login/access-tokens#extending )

For long term - when Device Login will be launched for Public ( https://developers.facebook.com/docs/facebook-login/using-login-with-devices ) - we will use it instead.

**Comment by lsoltero** [comment]
The Device Login procedure looks interesting.  However, there are two concerns.
1. It still requires user interaction.  An 8 digi code is displayed to the user who then copies it down, goes to a browser on another computer, logins to FB, and then enters the code.   Once this is done the device polls until it retrieves an access_token from FB which it then uses to post.

2. Although not explicitly stated the access_token returned by FB is probably either a standard short term (1hr) or long term (60day max) token which could expire if the user does not use the device to post to FB within the expiration period.

The nice thing about automatic_authentication is that once the user provides you with their FB authentication email/pw access to the users account for posting never expires. So the script could sit idle for 6 months and then post without issue unless the user changes his password.

What we need is a replacement for the post_offline token which was deprecated many years ago.

One thought that I have been meaning to investigate is using twitter to post to FB.  Twitter has static tokens that never expire.  They also have an agreement with FB for cross posting.  What I don't know is if the tokens provided to twitter by FB expire.  I know that twitter and FB have a special relationship so my hope is that tokens provided by FB to twitter are of a different nature than the ones we have access to.  The only way I know to test this is to setup a dummy FB and Twitter account, link them together,  and then wait > 60 days before posting.

Any thoughts on this would greatly be appreciated.

--luis
