### ISSUE TITLE
FBConole: Inconsistente state

### ISSUE THREAD

**Issue by pkcinco** [fbsamples/fbconsole#31]
I saw this cool library but I've been having issues trying to authenticate without login window. 

```
import fbconsole as F

F.AUTH_SCOPE = ['publish_stream']

F.automatically_authenticate(
    username,     # facebook username for authentication
    password,     # facebook password for authentication
    APP_SECRET,   # "app secret" from facebook app settings
    'http://127.0.0.1:8080', # redirect uri specified in facebook app settings    
    True
    )

```

Here is my stack trace...really need some help here please

Traceback (most recent call last):
  File "facebook-stream.py", line 11, in <module>
    'http://127.0.0.1:8080' # redirect uri specified in facebook app settings  
  File "build/bdist.macosx-10.8-intel/egg/fbconsole.py", line 425, in automatically_authenticate
AssertionError: Inconsistent state: ngG3UMD2kO3h3cSerlHYNsJSEtb0D8/ != ngG3UMD2kO3h3cSerlHYNsJSEtb0D8

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
