### ISSUE TITLE
Problem posting status in facebook

### ISSUE THREAD

**Issue by el3ctron** [fbsamples/fbconsole#35]
I use your amazing software but in the last days i have a problem posting status in facebook

Traceback (most recent call last):
  File "/opt/mis_scripts/publicarenfacebook", line 103, in <module>
    fbconsole.post('/me/feed', {'message': cadena})
  File "build/bdist.linux-x86_64/egg/fbconsole.py", line 763, in post
  File "build/bdist.linux-x86_64/egg/fbconsole.py", line 667, in post
  File "build/bdist.linux-x86_64/egg/fbconsole.py", line 280, in _safe_json_load
  File "build/bdist.linux-x86_64/egg/fbconsole.py", line 277, in _safe_url_load
fbconsole.OAuthException: Error validating access token: Session has expired on Thursday, 07-May-15 03:00:00 PDT. The current time is Thursday, 07-May-15 04:30:19 PDT.

i actualize the token but appears the same message

when i try the other authentication it says

Traceback (most recent call last):
  File "8txt2facebook2", line 19, in <module>
    redirect_uri
  File "build/bdist.linux-x86_64/egg/fbconsole.py", line 413, in automatically_authenticate
  File "build/bdist.linux-x86_64/egg/mechanize/_mechanize.py", line 524, in select_form
mechanize._mechanize.FormNotFoundError: no form matching nr 0

thanks for your answer!

**Comment by kchr** [comment]
How are you supplying your access token? 

fbconsole automatically read and use the token found in a file called ".fb_access_token", if such file exists in the current directory. This is the recommended way to supply an access token without having to authenticate manually. Note that it reads from **the environment's current directory**, not the directory where fbconsole module is located.

Setting the global variable fbconsole.ACCESS_TOKEN works but **will be overwritten** by any token found in that file.

**Comment by psineur** [comment]
Hey! Thanks for providing detailed feedback. There is a possibility that this issue can be solved with #37 .
I will create a separate branch for it, so we can test it before shipping to everyone.

**Comment by psineur** [comment]
My current suggestion would be to delete .fb_access_token from directory.
But we want to do something with expiring tokens.

Graph Explorer has Refresh functionality for this, but if you using mechanize - simple re-auth with browser poping up again may be not a solution for you.

@el3ctron Could you please share the scenario, how you're using fbconsole, so we can come up with something that will work the best for your case?
Thanks!

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
